### ISSUE TITLE
Unable to push to repo (ssh issue?)

### ISSUE THREAD

**Issue by rschwabco** [hasura/gitkube#128]
After following the setup instructions:
```
kubectl create -f https://raw.githubusercontent.com/hasura/gitkube/master/manifests/gitkube-setup.yaml

#expose gitkubed service
kubectl --namespace kube-system expose deployment gitkubed --type=LoadBalancer --name=gitkubed
```

I've set this repo up:

```
apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  name: my-app-remote
  namespace: default
spec:

# Insert ssh-keys for allowing users to git push
  authorizedKeys:
  - |
    "ssh-rsa AAAA........"  #content of ~/.ssh/id_rsa.pub 

# Provide registry details: https://github.com/hasura/gitkube/blob/master/docs/registry.md
  registry:
    url: "services.azurecr.io"
    credentials:
      secretRef: services-regsecret                # Name of docker-registry secret

# Define deployment rules
  deployments:
  - name: my-app                             # Name of K8s deployment which is updated on git push
    containers: 
    - name: my-app                           # Name of container in the deployment which is built during git push
      path: .                   # Docker build context path in the git repo
      dockerfile: ./Dockerfile  # Location of Dockerfile for the source code
```

For
```
kubectl get remote my-app-remote -o yaml
```

I get 
```
ssh://default-my-app-remote@40.64.64.125/~/git/default-my-app-remote
```

I then set up the remote:
```
git remote add release ssh://default-my-app-remote@40.64.64.125/~/git/default-my-app-remote
```

When I push, it failes with
```
The authenticity of host '40.64.64.125 (40.64.64.125)' can't be established.
ECDSA key fingerprint is SHA256:lOqGRBz/OyFYKwkUbrZrWSAYqWPjPGp1x8moUj9ci18.
Are you sure you want to continue connecting (yes/no/[fingerprint])?
Host key verification failed.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

What could possibly be going wrong?
