### ISSUE TITLE
groupadd: Not a valid group name

### ISSUE THREAD

**Issue by majodev** [hasura/gitkube#87]
Hi,

It seems like naming a remote is subject to certain limitations as `groupadd` is executed ([potentially 32chars?](https://unix.stackexchange.com/questions/11477/what-are-the-allowed-group-names-for-groupadd)).

**Example**

```yaml
apiVersion: gitkube.sh/v1alpha1
kind: Remote
metadata:
  name: app-remote
  namespace: my-really-really-really-long-ns
```

```bash
k logs po/gitkubed
Setting up git remotes
Configuring : my-really-really-really-long-ns-app-remote
Adding user `my-really-really-really-long-ns-app-remote' ...
Adding new group `my-really-really-really-long-ns-app-remote' (1000) ...
groupadd: 'my-really-really-really-long-ns-app-remote' is not a valid group name
adduser: `/usr/sbin/groupadd -g 1000 my-really-really-really-long-ns-app-remote' returned error code 3. Exiting.
```

Is there any way to overwrite the computed `my-really-really-really-long-ns-app-remote` identifier so groupadd can run through?
